name: kora
description: Navigateur et gestionnaire de téléchargements sans publicité.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  dio: ^5.7.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  share_plus: ^10.0.0
      webview_windows: ^0.4.0
flutter:
  uses-material-design: true
